### ISSUE TITLE
Be able to select all dictionaries in the initial "indexing" screen

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/nakshatra-app#4]
Initially, the app asks for the user to select dictionaries (present in dictdata directory) to index. 
I have 100+ dictionaries installed on my phone - it is not practical to check 100 boxes. there should be a "select all" box.

**Comment by damooo** [comment]
added annaa, and also added a counter indicating how many dictionaries are selected. and about 100+ dictionaries, i doubt weather it can handle those many. problem is it loads all .idx files into datastructures in RAM, and thus RAM may get overloaded. in practice, it may handle upto some 25 dictionaries well. We need to improve it's indexing algorithms so that we need not to load all idx files at a time into RAM. for example golden dict creates indices of size 8MB for some five large dictionaries. soon i will get familier with structures like B-Trees, etc, so that we can index in an effective manner.

**Comment by vvasuki** [comment]
oh! loading the word list into the RAM is a bad idea. And there is no need for us to "reinvent" the concept of a memory-efficient fast database. You can just use whatever Android offers - https://developer.android.com/training/data-storage/room/ ..
